cloud:
  aws:
    credentials:
      accessKey: AKIATAIHYCWHJN45GOHC
      secretKey: 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
    s3:
      bucket: malgo.images
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error