spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - data-local
      - cloud

security:
  jwt:
    token:
      validtime:
        access: 31557600000
        refresh: 31557600000
        clientSecret: 3600000
      secretkey: jwtsecretKeyhastolonghowlongidontknow