malgo:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:13306/malgo?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:13306/malgo?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    user: root
    password: root
    sql-migration-suffixes: sql
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    sql: debug